<?xml version="1.0"?>
<!DOCTYPE books
[
<!ELEMENT books (book+)>

    <!ELEMENT book (author,title,genre,price,review)>
    <!ATTLIST book  id CDATA  #REQUIRED >

    <!ELEMENT author (#PCDATA)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT genre (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT review (#PCDATA)>
]>
<books>
    <book id="bk001">
        <author>Writer</author>
        <title>The First Book</title>
        <genre>Fiction</genre>
        <price>44.95</price>
        <review>An amazing story of nothing.</review>
    </book>

    <book id="bk002">
        <author>Poet</author>
        <title>The Poetâ€™s First Poem</title>
        <genre>Poem</genre>
        <price>24.95</price>
        <review>Least poetic poems.</review>
    </book>
</books>